app/urls.py
from django.urls import path
from . import views
from .views import IndexList, NewDetailsView,PressDetailViews,EventDetailView,\
    NewsPressListView,EventListView,GalleryListViews,GalleryDetailView,\
    VideoListView,Members,AboutDetailtView,ManifestonList,LifeTimeMember,OrdinaryMemberlistView,BranchListView

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('about/<slug:about_slug>',AboutDetailtView.as_view(), name='about' ),
    path('news',NewsPressListView.as_view(), name='news' ),
    path('news/<slug:news_slug>',NewDetailsView.as_view(), name='news-details'),
    path('press/<slug:press_slug>',PressDetailViews.as_view(), name='press-details'),
    path('event', EventListView.as_view(), name='events'),
    path('event/<slug:event_slug>', EventDetailView.as_view(), name='event-details'),
    path('gallery', GalleryListViews.as_view(), name="gallery"),
    path('gallery/<slug:img_slug>', GalleryDetailView.as_view(), name="gallery-details"),
    path('videos', VideoListView.as_view(), name='videos'),
    path('members', Members.as_view(), name='members'),
    path('members/life-time-members', LifeTimeMember.as_view(), name='lifetimemembers'),
    path('members/ordinary-members', OrdinaryMemberlistView.as_view(), name='ordinaryMember'),
    # path('registration', views.registration, name='registration'),
    path('donation', views.donation, name='donation'),
    path('ordeinary/registration', views.ordinary_member_registration, name='registration'),
    path('manifeston', ManifestonList.as_view() , name='manifeston'),
    path('branch', BranchListView.as_view() , name='branchlist'),



    # translate language url
    path("set_language/<str:language>", views.set_language, name="set-language"),
    # end tanslate language url 

    # path('about',views.about, name='about'),
    path('vission', views.vission, name='vission'),
    path('executive-members', views.executivemembers, name='exe-members'),
    
    path('notice', views.notice, name='notice'),
    
    path('notice/details', views.notice_details, name='notice_details'),
    # path('gallery', views.imagegallery, name='gallery'),
    path('gallery/acd-images', views.innerimage, name='inner-gallery'),
    # path('videos', views.videogallery, name='videos'),
    path('transparency', views.transparency, name='transparency'),
    path('login', views.login, name='login'),
 
]

dashboard/urls.py
from django.urls import path
from . import views
app_name= 'dashboard'

urlpatterns = [
    path('',views.login, name='login'),

    path('about/<slug:slug>', views.about, name='about'),
    path('about/update/about', views.updateabout, name='updateabout'),
    path('manifesto', views.manifesto, name='manifesto'),
    path('manifesto/delete', views.deletemanifesto, name="deletemanifesto"),
    path('manifesto/create', views.createmanifesto, name='createmanifesto'),
    path('generalinfo', views.general_info, name='general_info'),
    path('bank-details', views.bankdetails, name='bankdetails'),

    path('index',views.index, name='index'),
    path('logout', views.userlogout, name='logout'),
    path('news', views.news, name='news'),
    path('news/create', views.create, name='create_news'),
    path('news/<slug:slug>', views.newsdetails, name='newsdetail'),
    path('news/update/<slug:slug>', views.newsupdate, name='news_update'),
    path('news/update', views.update_news, name='update_news'),
    path('news/<slug:slug>/delete', views.newsdelete, name='news_delete'),
   
    path('events', views.events, name='events'),
    path('event/create', views.create_event, name='event_create'),
    path('event/<slug:slug>', views.uppdateevents, name='update_evente'),
    path('event/view/<slug:slug>', views.viewevent, name='event_view'),
    path('evente/delete/<slug:slug>', views.deleteevent, name='delete_event'),

    path('press', views.press, name='press'),
    path('press/view/<slug:slug>', views.viewpress, name='viewpress'),
    path('press/update/<slug:slug>', views.updatepress, name='updatepress'),
    path('press/delete/<slug:slug>', views.deletepress, name='deltepress'),
    path('press/create', views.create_press, name='create_press'),


    path('executive_member', views.executivemember, name='executivemember'),
    path('executive_member/update', views.updatemember, name="updatemember"),
    path('executive_member/create', views.create_new_member, name="create_new_mem"),
    path('executive_member/delete', views.deleteExecutiveMember, name="exe_delete"),

    path('ordinary_member/verify', views.verified_ordinary_member, name="verifi_member"),
    path('ordinary_member/unverify', views.ordinarymember_unrified, name="ordinary_member_unverifed"),
    path('ordinary_delte', views.ordinary_delete,name="delete_ordinary"),
    path('ordinary_details', views.unverifydetails, name='unverifed_details'),
    path('unordinary_delete', views.unverified_delete, name="unordinary_delete"),
    path('ordinary/verify_details', views.view_ordinary_member, name='ordinary_details'),
    path('gallery', views.gallery, name='gallery'),
    path('gallery/<slug:slug>', views.editgallery, name="editgallery"),
    path('gallery/image/delete', views.deleteimage, name='deleteimage'),
    path('ablum/delete', views.deletealbum, name='deletealbum'),
    path('album/create', views.createnewalbum, name="createnewalbum"),
    path('bannar_image', views.bannar_image, name='bannar_image'),
    path('bannar/delete', views.delete_bannar_image, name="delete_bannar_image"),
    path('notification', views.notification, name='notification'),
    path('video-gallery', views.videogallery, name='videogallery'),
    path('video/delete', views.delete_video, name='delete_video'),
    path('branch-list', views.branchlist, name='branchlist'),
    path('branch/delete', views.deletebranch, name='deletebranch'),
    path('branch/edit', views.editbranch, name='editbranch'),
]

tandukarsamaj/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns=[
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('dashboard/', include('dashboard.urls')),
 ]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'app.views.error_404'


# urlpatterns=[
#     path('i182/', include("django.conf.urls.i18n")),
#  ]

# urlpatterns += i18n_patterns(
#     path( _('admin/'), admin.site.urls),
#     path('', include('app.urls')),
#     path('dashboard/', include('dashboard.urls')),
#     prefix_default_language=False,
# )+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# urlpatterns = [
#     *i18n_patterns(*urlpatterns, prefix_default_language=False),
#     ]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render,HttpResponse, HttpResponseRedirect,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from . decorators import login_required
from django.contrib import messages
from django.contrib import auth
from . new_file_handler import validate_file
from app.models import News, Event,Press,ExecutiveMember,OrdinaryMember,About,AboutUs,\
    Manifesto,ContactInfo,BankDetails,Image,Gallery,BannarImage,NoticeBoard,Video,Branch

def login(request):
    try:
        if request.user.is_authenticated:
            return render(request,'dashboard/index.html')

        if request.method =="POST":
            username = request.POST['username']
            password = request.POST['password']
            user_obj = User.objects.filter(username= username)
            if not user_obj.exists():
                messages.error(request,"Invalid username...")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                
            
            user_obj = authenticate(username=username, password=password)
            if user_obj and user_obj.is_superuser:
                auth.login(request, user_obj)
                return redirect('dashboard:index')
            
            messages.error(request,'Inavlid Password')
            return redirect('dashboard:login')
            
        return render(request,'dashboard/login.html')
            

    except Exception as e:
        # print(e)
        messages.error(request,'something wrong...')
        return redirect('dashboard:login')


@login_required
def index(request):
    news = News.objects.all()[:5]
    press = Press.objects.all()[:5]
    return render(request,'dashboard/index.html',{'news':news,
                                                  'press':press
                                                  })

@login_required
def userlogout(request):
    auth.logout(request)
    messages.info(request,"logout successfully..")
    return redirect('dashboard:login')


@login_required
def news(request):
    allnews = News.objects.all().order_by('id')
    return render(request,'dashboard/news.html',{'allnews':allnews})

@login_required
def newsdetails(request, slug):
    news = News.objects.get(news_slug= slug)
    return render(request,'dashboard/view.html',{'news':news})


@login_required
def newsupdate(request,slug):
    news = get_object_or_404(News, news_slug= slug)
    return render(request,'dashboard/updateform.html',{'news':news})


@login_required 
def update_news(request):
    if request.method == "POST":
        newsid= request.POST['newsid']
        news = get_object_or_404(News, id = newsid)
        news.title = request.POST['title']
        news.discriptions = request.POST['discription']
        news.image= request.FILES['image']
        news.save()
        messages.success(request,'news update successfully...')
        return render("dashboard:news")


# class NewsUpdate(UpdateView):
#     model = News
#     fields = [
#         "title",
#         "image",
#         "discriptions"
#     ]
#     slug_field = 'news_slug'
#     slug_url_kwarg = 'news_slug'
#     template_name="dashboard/updateform.html"
#     success_url = '/dashboard/news'



@login_required
def create(request):
    if request.method == "POST":
        title = request.POST['title']
        discription = request.POST['discription']
        print(discription)
        image = request.FILES['image']
        if validate_file(image):
            new_news = News(title = title,
                            image = image,
                            discriptions = discription
                            )
            new_news.save()
            messages.success(request,"create successfully..")
            return redirect('dashboard:news')
        else:
            messages.warning(request,'file not match...')
            return render(request,'dashboard/createform.html')

    else:
        return render(request,'dashboard/createform.html')
    
def newsdelete(request, slug):
    try:
        news = News.objects.get(news_slug= slug)
        news.delete()
        messages.success(request,'Deleted successfully...')
        return redirect('dashboard:news')
    
    except Exception as e:
        messages.success(request,'objects doesnot found...')
        return redirect('dashboard:news')
   

@login_required
def events(request):
    if request.method == "POST":
        pass
    else:
        allevents = Event.objects.all().order_by('id')
        return render(request,'dashboard/events.html',{'events':allevents})

@login_required
def uppdateevents(request, slug):
    event = Event.objects.get(event_slug= slug)
    if request.method =="POST":
        event.title = request.POST['title']
        print(request.FILES['image'])
        if request.FILES['image']:
            event.image = request.FILES['image']
        event.discriptions = request.POST['discription']
        event.save()
        messages.success(request,"update successfully..")
        return redirect('dashboard:events')
    else:
        return render(request,'dashboard/eventupdateform.html',{'event':event})
    
@login_required
def viewevent(request,slug):
    try:
        event = Event.objects.get(event_slug = slug)
        return render(request,'dashboard/eventview.html',{'event':event})
    
    except Exception as e:
        print(e)
        messages.warning(request,"event doesnot exites.")
        return redirect('dashboard:events')

@login_required
def create_event(request):
    if request.method == "POST":
        title = request.POST['title']
        discription = request.POST['discription']
        image = request.FILES['image']
        if validate_file(image):
            new_event = Event(title = title,
                            image = image,
                            discriptions = discription
                            )
            new_event.save()
            messages.success(request,"update successfully..")
            return redirect('dashboard:events')
        else:
            messages.warning(request,'file not match...')
            return render(request,'dashboard/eventcreate.html')

    else:
        return render(request,'dashboard/eventcreate.html')
       

@login_required 
def deleteevent(request, slug):
    try:
        event = Event.objects.get(event_slug = slug)
        event.delete()
        messages.info(request,'event deleted...')
        return redirect('dashboard:events')
    except Exception as e:
        print(e)
        messages.warning(request,'not found...')
        return redirect('dashboard:events')



@login_required
def press(request):
    allpress= Press.objects.all().order_by('id')
    return render(request,'dashboard/press.html',{'presses':allpress})


@login_required
def create_press(request):
    if request.method == "POST":
        title = request.POST['title']
        discription = request.POST['discription']
        image = request.FILES['image']
        if validate_file(image):
            new_press = Press(title = title,
                            image = image,
                            discriptions = discription
                            )
            new_press.save()
            messages.success(request,"create successfully..")
            return redirect('dashboard:press')
        else:
            messages(request,'file not match...')
            return render(request,'dashboard/createpress.html')

    else:
        return render(request,'dashboard/createpress.html')
    

@login_required 
def viewpress(request, slug):
    press = Press.objects.get(press_slug= slug)
    return render(request,'dashboard/pressview.html',{'press':press})

@login_required
def updatepress(request, slug):
    if request.method =="POST":
        try:
            press = Press.objects.get(press_slug= slug)
            press.title = request.POST['title']
            if validate_file(request.FILES['image']):
                press.image = request.FILES['image']
            press.discriptions = request.POST['discription']
            press.save()
            messages.success(request,'update successfully...')
            return redirect('dashboard:press')
            
        except Exception as e:
            print(e)
            messages.warning(request,'something wrong....')
            return redirect('dashboard:press')

    else:
        try:
            press = Press.objects.get(press_slug= slug)
            return render(request,'dashboard/pressupdate.html',{'press':press})
        
        except Exception as e:
            print(e)
            messages.warning(request,'some thing wrong..')
            return redirect("dashboard:press")

@login_required 
def deletepress(request, slug):
    try:
        press = Press.objects.get(press_slug = slug)
        press.delete()
        messages.info(request,'press deleted...')
        return redirect('dashboard:press')
    except Exception as e:
        print(e)
        messages.warning(request,'not found...')
        return redirect('dashboard:press')

@login_required
def executivemember(request):
    members = ExecutiveMember.objects.all()
    return render(request,'dashboard/executivemember.html',{'members':members})



@login_required
def updatemember(request):
    if request.method == "POST":
        id = request.POST['memberid']
        member = ExecutiveMember.objects.get(id = id)
        member.full_name= request.POST['fullname']
        member.position =request.POST['position']
        member.phone_number = request.POST['phone']
        if validate_file(request.FILES['image']):
            member.image = request.FILES['image']
            member.save()
            messages.success(request,"update successfully..")
            return redirect('dashboard:executivemember')
        else:
            messages.warning(request,'something wrong !..')
            return redirect('dashboard:executivemember')
        

dashboard/templates/dashboard/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<!-- index.html  21 Nov 2019 03:44:50 GMT -->
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Nepal Tandukar Samaj | 
    {%block title %}
    
    {% endblock %}
  </title>
  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'dashboard/assets/css/app.min.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/assets/bundles/summernote/summernote-bs4.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/assets/bundles/codemirror/lib/codemirror.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/assets/bundles/codemirror/theme/duotone-dark.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/assets/bundles/jquery-selectric/selectric.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/assets/bundles/chocolat/dist/css/chocolat.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'dashboard/assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'dashboard/assets/css/components.css' %}">
  <!-- Custom style CSS -->
  <link rel="stylesheet" href="{% static 'dashboard/assets/css/custom.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'app/assets/img/tandukar-samaj-logo.png' %}" />

  
</head>

<body>
  <div class="loader"></div>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar sticky">
        <div class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg
									collapse-btn"> <i data-feather="align-justify"></i></a></li>
            <li><a href="#" class="nav-link nav-link-lg fullscreen-btn">
                <i data-feather="maximize"></i>
              </a></li>
            
          </ul>
        </div>
        <ul class="navbar-nav navbar-right">
          
          
          <li class="dropdown"><a href="#" data-toggle="dropdown"
              class="nav-link dropdown-toggle nav-link-lg nav-link-user"> <img alt="image" src="{% static 'dashboard/assets/img/user.png' %}"
                class="user-img-radious-style"> <span class="d-sm-none d-lg-inline-block"></span></a>
            <div class="dropdown-menu dropdown-menu-right pullDown">
              <div class="dropdown-title">Hello {{request.user.username}}</div>
              
              <div class="dropdown-divider"></div>
              <a href="{% url 'dashboard:logout' %}" class="dropdown-item has-icon text-danger"> <i class="fas fa-sign-out-alt"></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar sidebar-style-2">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="{% url 'dashboard:index' %}"> 
              <img src="{% static 'app/assets/img/tandukar_logo.png' %}" style="height:100%; width:100%;">
               {% comment %} <span
                class="logo-name text-danger ">नेपाल तण्डुकार </span> {% endcomment %}
            </a>
          </div>
          <ul class="sidebar-menu">
            <li class="menu-header">Main</li>
            <li class="dropdown active">
              <a href="{% url 'dashboard:index' %}" class="nav-link"><i data-feather="monitor"></i><span>Dashboard</span></a>
            </li>
            
           
            <li class="menu-header">Pages</li>

            <li class="">
              <a href="{% url 'dashboard:notification' %}" class="nav-link"><i data-feather="command"></i><span>Notification</span></a>
            </li>


            <li class="">
              <a href="{% url 'dashboard:news' %}" class="nav-link"><i data-feather="command"></i><span>News</span></a>
            </li>

            <li class="dropdown">
              <a href="{% url 'dashboard:events' %}"  class="nav-link"><i data-feather="command"></i><span>Events</span></a>
            </li>

            <li class="dropdown">
              <a href="{% url 'dashboard:press' %}"  class="nav-link"><i data-feather="command"></i><span>Press</span></a>
            </li>

            <li class="dropdown">
              <a href="{% url 'dashboard:executivemember' %}"  class="nav-link"><i data-feather="command"></i><span>Executive Member</span></a>
            </li>

            <li class="dropdown">
              <a href="{% url 'dashboard:manifesto' %}"  class="nav-link"><i data-feather="command"></i><span>Manifesto</span></a>
            </li>


            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown">
                <i data-feather="command"></i>
                <span>Ordinary Member</span>
              </a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'dashboard:verifi_member' %}">Verified Member</a></li>
                    <li><a href="{% url 'dashboard:ordinary_member_unverifed' %}">Unverified Member</a></li>
                  </ul>
            </li>
           

            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown">
                <i data-feather="command"></i>
                <span>About Us</span>
              </a>
                  <ul class="dropdown-menu">
                    {% for item in aboutctg %}
                          <li><a class="dropdown-item" href="{% url  'dashboard:about' item.about_slug %}">{{ item.title }}</a></li>
                    {% endfor %}
                  </ul>
            </li>


           
            <li class="menu-header">Branch</li>
            <li class="dropdown">
              <a href="{% url 'dashboard:branchlist' %}"  class="nav-link"><i data-feather="home"></i><span><span>Add Branch</span></a>
            </li>



            <li class="menu-header">Media</li>
            <li class="dropdown">
              <a href="{% url 'dashboard:gallery' %}"  class="nav-link"><i data-feather="image"></i><span><span>Gallery</span></a>
            </li>
            <li class="dropdown">
              <a href="{% url 'dashboard:bannar_image' %}"  class="nav-link"><i data-feather="flag"></i><span><span>Bannar Image</span></a>
            </li>

            <li class="dropdown">
              <a href="{% url 'dashboard:videogallery' %}"  class="nav-link"><i data-feather="play"></i><span><span>Video Gallery</span></a>
            </li>

            

            <li class="menu-header"> Information</li>
            <li class="dropdown">
              <a href="{% url 'dashboard:general_info' %}"  class="nav-link"><i data-feather="book"></i><span><span>General Information</span></a>
            </li>
            <li class="dropdown">
              <a href="{% url 'dashboard:bankdetails' %}"  class="nav-link"><i data-feather="home"></i><span><span>Bank Details</span></a>
            </li>
            

            {% comment %} <li class="menu-header">Website settings</li> {% endcomment %}
            
           

            {% comment %} <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown">
                <i class="fa fa-cog"></i>
                <span>Settings</span>
              </a>
                  <ul class="dropdown-menu">
                    <li><a href="">Keywords</a></li>
                    <li><a href="">Discription</a></li>
                    <li><a href="">Auth</a></li>
                  </ul>
            </li> {% endcomment %}
           
          </ul>
        </aside>
      </div>
      {% block content %}

      {% endblock %}
      <footer class="main-footer">
        <div class="footer-left">
          <a href="">Kitwosd</a></a>
        </div>
        <div class="footer-right">
        </div>
      </footer>
    </div>
  </div>

   <!-- General JS Scripts -->
   <script src="{% static 'dashboard/assets/js/app.min.js' %}"></script>
   <!-- JS Libraies -->
   <script src="{% static 'dashboard/assets/bundles/summernote/summernote-bs4.js' %}"></script>
   <script src="{% static 'dashboard/assets/bundles/codemirror/lib/codemirror.js' %}"></script>
   <script src="{% static 'dashboard/assets/bundles/codemirror/mode/javascript/javascript.js' %}"></script>
   <script src="{% static 'dashboard/assets/bundles/jquery-selectric/jquery.selectric.min.js' %}"></script>
   <script src="{% static 'dashboard/assets/bundles/ckeditor/ckeditor.js' %}"></script>
   <!-- Page Specific JS File -->
   <script src="{% static 'dashboard/assets/js/page/ckeditor.js' %}"></script>
   <script src="{% static 'dashboard/assets/js/page/gallery1.js' %}"></script>
   <!-- Template JS File -->
   <script src="{% static 'dashboard/assets/js/scripts.js' %}"></script>
   <!-- Custom JS File -->
   <script src="{% static 'dashboard/assets/js/custom.js' %}"></script>
 
   <!-- JS Libraies -->
   <script src="{%static 'dashboard/assets/bundles/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>

  
</body>



<!-- index.html  21 Nov 2019 03:47:04 GMT -->
</html>

dashboard/templates/dashboard/events.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
Event
{% endblock %}
{% block content %}

<!-- table start-->
<div class="main-content">
  <section class="section">
    <div class="section-body">
     
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4>Advanced Table</h4>
              
              <div class="card-header-form">
                
                <form>
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                      <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </form>
              </div>

              <div class="btn btn-warning"><a href="{% url 'dashboard:event_create' %}" class="text-white" style="text-decoration:none;">Create</a></div>

            </div>
            <div class="card-body p-0">
              <div class="table-responsive">
                <table class="table table-striped">
                  <tr>
                    <th class="text-center">
                      S.N
                    </th>
                    <th>Title </th>
                    <th>Image</th>
                    <th>Discription</th>
                    <th>Action</th>
                  </tr>
                  {% for item in events %}
                  <tr class="pt-4">
                    <td class="p-0 text-center">
                      {{item.id}}
                    </td>
                    <td>{{item.title}}</td>
                    
                    <td>
                      <img alt="image" src="{{item.image.url}}" class="" width="35"
                        data-toggle="tooltip" title="Wildan Ahdian">
                    </td>
                    <td >{{item.discriptions|safe|truncatewords:100}}</td>
                   
                    <td>
                      <a href="{% url  'dashboard:event_view' item.event_slug %}" class="btn btn-primary"><i class="fas fa-eye"></i></a>
                      <a href="{% url 'dashboard:update_evente' item.event_slug  %}" class="btn btn-success"><i class="fas fa-pen"></i></a>
                      <a href="{% url 'dashboard:delete_event' item.event_slug %}" class="btn btn-danger"><i class="fas fa-trash "></i></a>
                    </td>
                  </tr>
                  {% endfor %}

                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </section>
  
</div>
<!-- end table-->



{% endblock %}

dashboard/templates/dashboard/press.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
Event
{% endblock %}
{% block content %}

<!-- table start-->
<div class="main-content">
  <section class="section">
    <div class="section-body">
     
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4>Press Table</h4>
              
              <div class="card-header-form">
                
                <form>
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                      <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </form>
              </div>

              <div class="btn btn-warning"><a href="{% url 'dashboard:create_press' %}" class="text-white" style="text-decoration:none;">Create</a></div>

            </div>
            <div class="card-body p-0">
              <div class="table-responsive">
                <table class="table table-striped">
                  <tr>
                    <th class="text-center">
                      S.N
                    </th>
                    <th>Title </th>
                    <th>Image</th>
                    <th>Create Date</th>
                    <th>Action</th>
                  </tr>
                  {% for item in presses %}
                  <tr class="pt-4">
                    <td class="p-0 text-center">
                      {{item.id}}
                    </td>
                    <td>{{item.title}}</td>
                    
                    <td>
                      <img alt="image" src="{{item.image.url}}" class="" width="35"
                        data-toggle="tooltip" title="Wildan Ahdian">
                    </td>
                    <td >{{item.create_date}}</td>
                   
                    <td>
                      <a href="{% url 'dashboard:viewpress' item.press_slug %}" class="btn btn-primary"><i class="fas fa-eye"></i></a>
                      <a href="{% url  'dashboard:updatepress' item.press_slug %}" class="btn btn-success"><i class="fas fa-pen"></i></a>
                      <a href="{% url  'dashboard:deltepress' item.press_slug  %}" class="btn btn-danger"><i class="fas fa-trash "></i></a>
                    </td>
                  </tr>
                  {% endfor %}

                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </section>
  
</div>
<!-- end table-->



{% endblock %}